# Generated by Django 5.1.2 on 2024-10-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripmates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersona',
            name='stay_preferences',
        ),
        migrations.RemoveField(
            model_name='userpersona',
            name='traveler_type',
        ),
        migrations.RemoveField(
            model_name='userpersona',
            name='type_of_person',
        ),
        migrations.AddField(
            model_name='userpersona',
            name='accommodation_preference',
            field=models.CharField(choices=[('hotels', 'Hotels'), ('hostels', 'Hostels'), ('ashrams_dharamshaala', 'Ashrams/ Dharamshaala'), ('camping', 'Camping')], default='hotels', max_length=50),
        ),
        migrations.AddField(
            model_name='userpersona',
            name='destination_preference',
            field=models.CharField(choices=[('beaches', 'Beaches'), ('mountains', 'Mountains'), ('urban_cities', 'Urban Cities'), ('historical_sites', 'Historical Sites'), ('national_parks', 'National Parks')], default='beaches', max_length=50),
        ),
        migrations.AddField(
            model_name='userpersona',
            name='travel_frequency',
            field=models.CharField(choices=[('once_a_year', 'Once a year'), ('2-3_times_a_year', '2-3 times a year'), ('once_a_month', 'Once a month'), ('more_frequently', 'More frequently')], default='once_a_year', max_length=50),
        ),
        migrations.AddField(
            model_name='userpersona',
            name='trip_preferences',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('cultural_exploration', 'Cultural exploration'), ('partying_nightlife', 'Partying/Nightlife'), ('business', 'Business')], default='adventure', max_length=50),
        ),
        migrations.AddField(
            model_name='userpersona',
            name='trip_type',
            field=models.CharField(choices=[('planned', 'Planned'), ('spontaneous', 'Spontaneous'), ('mix_of_both', 'A mix of both')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpersona',
            name='transport_preference',
            field=models.CharField(choices=[('public_transportation', 'Public transportation (buses, trains, etc.)'), ('renting_a_car', 'Renting a car'), ('walking_biking', 'Walking/Biking'), ('private_transport', 'Private transport (taxis, Ubers, etc.)')], default='public_transportation', max_length=50),
        ),
    ]
