# Generated by Django 5.1.2 on 2024-10-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripmates', '0003_rename_id_appuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
