# Generated by Django 5.1.2 on 2024-10-20 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripmates', '0005_appuser_first_login_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_frequency', models.IntegerField()),
                ('trip_type', models.IntegerField()),
                ('itinerary_preference', models.IntegerField()),
                ('destination_preference', models.IntegerField()),
                ('accommodation_preference', models.IntegerField()),
                ('transport_preference', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tripmates.userpreference')),
            ],
        ),
    ]
