# Generated by Django 5.1.2 on 2024-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripmates', '0006_userpreference_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='accommodation_preference',
            field=models.IntegerField(choices=[(1, 'Hotels'), (2, 'Hostels'), (3, 'Ashrams/Dharamshaala'), (4, 'Camping')], default=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='destination_preference',
            field=models.IntegerField(choices=[(1, 'Beaches'), (2, 'Mountains'), (3, 'Urban Cities'), (4, 'Historical Sites'), (5, 'National Parks')], default=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='itinerary_preference',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Spontaneous'), (3, 'A mix of both')], default=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='transport_preference',
            field=models.IntegerField(choices=[(1, 'Public transportation (buses, trains, etc.)'), (2, 'Renting a car'), (3, 'Walking/Biking'), (4, 'Private transport (taxis, Ubers, etc.)')], default=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='travel_frequency',
            field=models.IntegerField(choices=[(1, 'Once a year'), (2, '2-3 times a year'), (3, 'Once a month'), (4, 'More frequently')], default=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='trip_type',
            field=models.IntegerField(choices=[(1, 'Adventure'), (2, 'Relaxation'), (3, 'Cultural exploration'), (4, 'Partying/Nightlife'), (5, 'Business')], default=1),
        ),
    ]
