# Generated by Django 5.1.2 on 2024-10-20 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripmates', '0007_alter_userpreference_accommodation_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tripmates.userpersona'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
